### PR TITLE
Added processor type as label on 'zcpc-processor-usage' metrics group

### PR DESCRIPTION
**Pull request by andy-maier**
See commit message.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0f4f63ca5ab2278b9730420234605d13427e353d
  * Your commit message body contains a line that is longer than 80 characters

Guidelines are available at https://github.com/zhmcclient/zhmc-prometheus-exporter/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 8190862e395396d811cd2f92fd393b5b4ccdfd08
  * Your commit message body contains a line that is longer than 80 characters

Guidelines are available at https://github.com/zhmcclient/zhmc-prometheus-exporter/blob/master/CONTRIBUTING.rst

---
This message was auto-generated by https://gitcop.com

**Review by amber-zhang — COMMENTED** [review]
The changes look right. thanks!

**Review by vkathir82 — APPROVED** [review]
Hi Andy, The changes are looking good. So I am merging the changes.

**Pull request merged**
