### PR TITLE
Documented the authorization requirements for the HMC userid

### PR DESCRIPTION
**Pull request by andy-maier**

### CODE REVIEW

**Review by vkathir82 — APPROVED** [review]
Permission updates with respect to managed objects access permissions are looks good w.r.t metrics access permissions. I am not merging it until Vance Morris who requested this change review's it.

**Comment by andy-maier** [comment]
@vmorris Vance, do you have a chance to review this PR?

**Comment by andy-maier** [comment]
Merging now.

**Comment by vmorris** [comment]
Sorry it took me so long to get back to this item - Thanks @andy-maier and @vkathir82 , lgtm

**Pull request merged**
